[package]
name = "internal"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.1"
# You only need serde if you want app persistence:
serde = { version = "1.0.228", features = ["derive"] }
